name: Trigger Men Shoes Pipeline

on:
  workflow_dispatch:  

  # schedule:
  #   - cron: '0 */2 * * *'  

jobs:
  trigger-public-workflow:
    runs-on: ubuntu-latest

    permissions:
        contents: write  
        packages: write  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
    
      - name: Set up environment and run script with secrets
        run: |
            echo "Setting up environment variables"
        env:
            SUPPLIER_URL: ${{ secrets.SUPPLIER_URL }}
            LOGIN: ${{ secrets.LOGIN }}
            PASSWORD: ${{ secrets.PASSWORD }}

      - name: Clone Private Repository
        run: |
          git clone https://${{ secrets.PROFILE_URL }}:${{secrets.PUBLIC_PAT}}@github.com/${{ secrets.PROFILE_URL_REPO }}.git private_repo
     
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: pip install pandas requests lxml selenium argparse

      - name: Scrape data
        run: |
            echo "Scraping data and generating CSV..."
            export SUPPLIER_URL="${{ secrets.SUPPLIER_URL }}"
            export LOGIN="${{ secrets.LOGIN }}"
            export PASSWORD="${{ secrets.PASSWORD }}"
            python /home/runner/work/supplier2_unified_structure/supplier2_unified_structure/get_data.py \
                        --filename "men_shoes.csv" --pages "1,5" "6,10" "11,15" "16,20" --urls "${{ secrets.MEN_SHOES }}" --n_collections=4 --collection="Men Shoes" --max_workers=4

      - name: Clean Data
        run: |
            python /home/runner/work/supplier2_unified_structure/supplier2_unified_structure/private_repo/clean_men_shoes.py --input_file "men_shoes.csv"
                
      - name: Commit changes from update.py
        run: |
            cd private_repo
            git config --local user.name "GitHub Action"
            git config --local user.email "action@github.com"
            git pull origin master --no-edit
            git add clean_data/men_shoes/

            # Commit changes if there are any
            git diff --cached --quiet || git commit -m "Commit changes from update.py"

            git push

      - name: Install Node.js dependencies 
        run: npm install axios csv-parser dotenv shopify-api-node fs
      
      - name: Iterate over the products
        run: node /home/runner/work/supplier2_unified_structure/supplier2_unified_structure/iterate_and_find.js
        env:
            SHOP: ${{ secrets.SHOP }}
            SHOPIFY_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ACCESS_TOKEN_MEN_SHOES }}
            ITERATE_AND_FIND: 'private_repo/clean_data/men_shoes/clean_men_shoes.csv'
            FOLDER: 'private_repo/clean_data/men_shoes/'

      - name: Preprocess data
        run: python /home/runner/work/supplier2_unified_structure/supplier2_unified_structure/preprocess.py --input_folder "private_repo/clean_data/men_shoes" --clean_file "clean_men_shoes.csv"
      
      - name: Update products
        run: node /home/runner/work/supplier2_unified_structure/supplier2_unified_structure/update_products.js
        env:
            SHOP: ${{ secrets.SHOP }}
            SHOPIFY_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ACCESS_TOKEN_MEN_SHOES }}
            TO_UPDATE: 'private_repo/clean_data/men_shoes/os_update_products.csv'


      - name: Set inventory 0
        run: node /home/runner/work/supplier2_unified_structure/supplier2_unified_structure/set_zero_inventory.js
        env:
            SHOP: ${{ secrets.SHOP }}
            SHOPIFY_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ACCESS_TOKEN_MEN_SHOES }}
            ZERO_INVENTORY: 'private_repo/clean_data/men_shoes/zero_inventory_shopify.csv'

      - name: Update costs
        run: node /home/runner/work/supplier2_unified_structure/supplier2_unified_structure/update_costs.js
        env:
            SHOP: ${{ secrets.SHOP }}
            SHOPIFY_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ACCESS_TOKEN_MEN_SHOES }}
            UPDATE_COSTS: 'private_repo/clean_data/men_shoes/different_costs.csv'

      - name: Commit changes from update.py
        run: |
            cd private_repo
            git config --local user.name "GitHub Action"
            git config --local user.email "action@github.com"
            git pull origin master --no-edit
            git add clean_data/men_shoes/

            # Commit changes if there are any
            git diff --cached --quiet || git commit -m "Commit changes from update.py"

            git push
